---
AWSTemplateFormatVersion: "2010-09-09"
Description: This is the first ckoudformation template to create S3 bucket
Resources:
  waleedS3Bucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: demobucket7754fhvb
