---
AWSTemplateFormatVersion: "2010-09-09"
Description: This is the first CloudFormation template to create S3 bucket and EC2 with parameters

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - label:
          default: "compute configuration"
        parameters:
          - InstanceTypeParameters

      - label:
          default: "storage configuration"
        parameters:
          - S3bucketnameparameter

Parameters:
  EC2amiID:
    Type: String
    Default: ami-084568db4383264d4

  InstanceTypeParameters:
    Type: String
    Default: t2.micro

  S3bucketnameparameter:
    Type: String

Resources:
  WaleedS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3bucketnameparameter

  WaleedEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameters
      ImageId: !Ref EC2amiID

